#!/usr/bin/env bash
#
# epcview install.sh — system-wide install on a Linux laptop / workstation.
#
# Usage:  sudo ./install.sh
#
# What it does:
#   1. Make sure python3, python3-venv, python3-pip are present (apt-installs
#      them if not).
#   2. Wipe any previous /opt/epcview-* directories so upgrades are clean.
#   3. Stage the source tree under /opt/epcview-<version>.
#   4. Build a venv there and install Python deps.
#   5. Drop a launcher at /usr/local/bin/epcview so any user can run
#      "epcview" without sudo.
#   6. Drop the matching uninstaller at /usr/local/sbin/epcview-uninstall.
#   7. Seed /etc/epcview/epcview.yaml with the bundled config if not already
#      present (so re-runs preserve your edits).

set -euo pipefail

if [[ "$EUID" -ne 0 ]]; then
    echo "✗ This installer needs root (writes to /opt, /usr/local, /etc)."
    echo "  Re-run with:  sudo $0"
    exit 1
fi

SCRIPT_DIR=$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)
SRC_DIR=$(dirname "$SCRIPT_DIR")          # one level up from deploy/
VERSION=$(awk -F'"' '/^__version__/ {print $2}' "$SRC_DIR/version.py")

if [[ -z "$VERSION" ]]; then
    echo "✗ Could not read version from $SRC_DIR/version.py"
    exit 1
fi

INSTALL_DIR="/opt/epcview-$VERSION"
LAUNCHER="/usr/local/bin/epcview"
UNINSTALLER="/usr/local/sbin/epcview-uninstall"
ETC_DIR="/etc/epcview"

echo "→ epcview $VERSION"
echo "  install dir : $INSTALL_DIR"
echo "  launcher    : $LAUNCHER"
echo "  uninstaller : $UNINSTALLER"
echo

# ── 1. Python prerequisites ───────────────────────────────────────────────
need_apt=()
command -v python3                >/dev/null 2>&1 || need_apt+=("python3")
python3 -c "import venv"          >/dev/null 2>&1 || need_apt+=("python3-venv")
python3 -m pip --version          >/dev/null 2>&1 || need_apt+=("python3-pip")

if [[ ${#need_apt[@]} -gt 0 ]]; then
    echo "→ Installing missing system packages: ${need_apt[*]}"
    if ! command -v apt-get >/dev/null 2>&1; then
        echo "✗ Missing ${need_apt[*]} but apt-get not found."
        echo "  Install them by hand (e.g. dnf, pacman) and re-run this script."
        exit 1
    fi
    apt-get update -qq
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq "${need_apt[@]}"
fi

# ── 2. Wipe old /opt/epcview-* (clean upgrade) ────────────────────────────
shopt -s nullglob
for d in /opt/epcview-*; do
    echo "  - removing previous install: $d"
    rm -rf "$d"
done
shopt -u nullglob

# ── 3. Stage source tree under /opt/epcview-<version> ────────────────────
mkdir -p "$INSTALL_DIR"
cp -r  "$SRC_DIR/main.py"          \
       "$SRC_DIR/cli.py"           \
       "$SRC_DIR/config.py"        \
       "$SRC_DIR/poller.py"        \
       "$SRC_DIR/state.py"         \
       "$SRC_DIR/version.py"       \
       "$SRC_DIR/epcview.yaml"     \
       "$SRC_DIR/requirements.txt" \
       "$SRC_DIR/README.md"        \
       "$SRC_DIR/nfs"              \
       "$SRC_DIR/deploy"           \
       "$INSTALL_DIR/"

# ── 4. Virtualenv + Python deps ───────────────────────────────────────────
echo "→ Building venv and installing deps"
python3 -m venv "$INSTALL_DIR/.venv"
"$INSTALL_DIR/.venv/bin/pip" install --quiet --upgrade pip
"$INSTALL_DIR/.venv/bin/pip" install --quiet -r "$INSTALL_DIR/requirements.txt"

# ── 5. World-readable / executable so non-root users can run it ──────────
chmod -R a+rX "$INSTALL_DIR"

# ── 6. /etc/epcview — seed default config, never overwrite a user edit ──
mkdir -p "$ETC_DIR"
cp -f "$SRC_DIR/epcview.yaml" "$ETC_DIR/epcview.yaml.example"
if [[ ! -e "$ETC_DIR/epcview.yaml" ]]; then
    cp "$SRC_DIR/epcview.yaml" "$ETC_DIR/epcview.yaml"
    echo "  - seeded $ETC_DIR/epcview.yaml"
else
    echo "  - kept existing $ETC_DIR/epcview.yaml"
fi
chmod -R a+rX "$ETC_DIR"

# ── 7. Launcher (any user) ───────────────────────────────────────────────
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Auto-generated by epcview install.sh — do not edit; re-run installer.
exec "$INSTALL_DIR/.venv/bin/python3" "$INSTALL_DIR/main.py" "\$@"
EOF
chmod 755 "$LAUNCHER"

# ── 8. Uninstaller (root) ─────────────────────────────────────────────────
mkdir -p "$(dirname "$UNINSTALLER")"
cp "$INSTALL_DIR/deploy/uninstall.sh" "$UNINSTALLER"
chmod 755 "$UNINSTALLER"

echo
echo "✔ epcview $VERSION installed."
echo
echo "  Run:                epcview"
echo "  System config:      $ETC_DIR/epcview.yaml   (edit hosts/ports)"
echo "  Per-user override:  ~/.config/epcview/epcview.yaml"
echo "  Uninstall:          sudo epcview-uninstall"
